### ISSUE TITLE
RedisFeatureFlagStore base_key argument is ignored

### ISSUE THREAD

**Issue by rusintez** [carta/flipper-client#25]
https://github.com/carta/flipper-client/blob/cd00ae1a3582c5cb7e661c5aa9b8a7b65b35a9e0/flipper/contrib/redis.py#L30
https://github.com/carta/flipper-client/blob/cd00ae1a3582c5cb7e661c5aa9b8a7b65b35a9e0/flipper/contrib/redis.py#L34

**Comment by adambom** [comment]
Fixed in version 1.1.0
