### ISSUE TITLE
Package Dependency Constraints Too Specific

### ISSUE THREAD

**Issue by jamesstonehill** [carta/flipper-client#37]
### The Problem
Most of the requirements in the setup.py file are constrained to a specific minor release version. This makes it hard to integrate this library with existing projects because often projects will have some these dependencies already required and if they are required at a different minor release version it might be impossible to resolve the dependency conflict.

```python
requirements = [
    "cachetools~=4.1.0",
    "python-consul~=1.0.1",
    "redis>=2.10.6,<4",
    "thrift~=0.13.0",
    "boto3~=1.9.83",
    "pyee==6.0.0",
]
```

For example, `cachetools`, `python-consul`, `boto3` and `pyee` are all tied to a specific minor releases, but because these projects all seem to adhere to semantic versioning, it should be safe to pin these to the major release version only. Even then, for many of these dependencies there might even be multiple major releases that are compatible with this library though this would need to be checked in the release notes of each library.

This issue results in problems like this:
https://github.com/carta/flipper-client/pull/36/files

### What should be done?

Change the setup.py file's requirements to look like this:
```python
requirements = [
    "cachetools~=4.1",
    "python-consul~=1.0",
    "redis>=2.10.6,<4",
    "thrift~=0.13.0",
    "boto3~=1.9",
    "pyee==6.0",
]
```

**Comment by jamesstonehill** [comment]
@r-kells @adambom This suggestion is similar to this MR:
https://github.com/carta/flipper-client/pull/34

Would you be able to review?

**Comment by adambom** [comment]
@jamesstonehill I'll try and address this tomorrow.

**Comment by adambom** [comment]
Release 1.2.7 is out
