### ISSUE TITLE
Equality Operator from Condition is not being constructed due to parsing error

### ISSUE THREAD

**Issue by DannyTamiru** [carta/flipper-client#48]
This might be a know issue or I may be missing something, but there doesn't seem to be a way to create Conditions with equality checks using the Condition constructor. 

The [EqualityOperator](https://github.com/carta/flipper-client/blob/3d0536887e1d72b6c100cd06d1b059f89b3e3f0e/flipper/conditions/operators/equality_operator.py#L20) uses `None` as its symbol, but splitting a check key into two parts will never give `None` explicitly. For example: 

`Condition(count__=0)` will result in the following empty string error:
```
cls = <class 'flipper.conditions.operators.operator.Operator'>, operator_symbol = ''

    @classmethod
    def factory(cls, operator_symbol: Optional[str]):
        try:
            return cls.OPERATOR_MAP[operator_symbol]()  # type: ignore
        except KeyError:
>           raise cls.InvalidSymbolError("Operator not supported: %s" % operator_symbol)
E           flipper.conditions.operators.operator.Operator.InvalidSymbolError: Operator not supported:

/usr/local/lib/python3.8/site-packages/flipper/conditions/operators/operator.py:46: InvalidSymbolError
```

Would it be better to make EqualityOperator's symbol something like 'eq' since NegationOperator's is 'ne'? Or maybe accounting for `None` in the factor method would be better?

**Comment by adambom** [comment]
Equality-based conditions can be created by using keyword arguments without the dunder syntax:

```python
condition = Condition(count=0)
```

See the readme for more: https://github.com/carta/flipper-client#conditions
