### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by eliasdorneles** [carta/flipper-client#49]
Hello,

Can we have a new minor release in order to benefit from the bugfix at: https://github.com/carta/flipper-client/commit/3d0536887e1d72b6c100cd06d1b059f89b3e3f0e ?

Thanks

**Comment by adambom** [comment]
Sorry for the delay! Release published: https://pypi.org/project/flipper-client/1.3.1/

**Comment by eliasdorneles** [comment]
Thank you!!
